package com.hihelloy.invincible.abilities;

import net.kyori.adventure.text.format.NamedTextColor;

public enum AbilityType {

    WISH("Wish",
    AbilityCategory.UTILITY,
    20000,
    NamedTextColor.AQUA,
    "Heal yourself with an almighty wish!", "Left click to heal"),

    INVULNERABILITY("Invulnerability", AbilityCategory.DEFENSE, 15000, NamedTextColor.BLUE,
    "Become nearly immune to all damage. Hold still after activating for maximum effect.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    COMBO_STRIKE("Combo Strike", AbilityCategory.OFFENSE, 4000, NamedTextColor.GOLD,
    "Unleash five rapid hits in quick succession on all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SONIC_CLAP("Sonic Clap", AbilityCategory.OFFENSE, 6000, NamedTextColor.WHITE,
    "Slam both hands together, releasing a shockwave that damages and pushes back enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ATOMIC_PUNCH("Atomic Punch", AbilityCategory.OFFENSE, 10000, NamedTextColor.RED,
    "Charge forward then detonate with a devastating punch. Deals massive damage on impact.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    REGENERATION("Regeneration", AbilityCategory.DEFENSE, 12000, NamedTextColor.GREEN,
    "Rapidly heal wounds over a short duration. Scaled by your Duration stat.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TREMOR_SLAM("Tremor Slam", AbilityCategory.OFFENSE, 8000, NamedTextColor.DARK_GREEN,
    "Slam the ground with full force, creating a shockwave that knocks back nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    WARCRY("Warcry", AbilityCategory.UTILITY, 18000, NamedTextColor.RED,
    "Let out a thunderous war cry that pushes all enemies away and briefly weakens them.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BERSERKER_RAGE("Berserker Rage", AbilityCategory.OFFENSE, 15000, NamedTextColor.DARK_RED,
    "Enter a rage state, massively boosting damage output and movement. Ends after a short duration.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    VELOCITY_DIVE("Velocity Dive", AbilityCategory.MOBILITY, 5000, NamedTextColor.BLUE,
    "Dive downward at extreme speed, dealing damage to anything below you on impact.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SHOCKWAVE_LANDING("Shockwave Landing", AbilityCategory.OFFENSE, 9000, NamedTextColor.AQUA,
    "Crash-land onto the ground with superhuman force, releasing a shockwave in all directions.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    RELENTLESS("Relentless", AbilityCategory.DEFENSE, 22000, NamedTextColor.BLUE,
    "Draw on sheer will and Viltrumite stubbornness to massively reduce incoming damage briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SUPERSONIC_STRIKE("Supersonic Strike", AbilityCategory.OFFENSE, 7000, NamedTextColor.BLUE,
    "Accelerate to supersonic speed and deliver a single impact strike to the nearest enemy.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    ENDURANCE("Endurance", AbilityCategory.DEFENSE, 20000, NamedTextColor.GRAY,
    "Tap into millennia of battle experience to shrug off damage for a short period.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TERROR_STRIKE("Terror Strike", AbilityCategory.OFFENSE, 5000, NamedTextColor.DARK_RED,
    "Strike with the force of a seasoned conqueror. Applies weakness to the target.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SPIN_DASH("Spin Dash", AbilityCategory.MOBILITY, 6000, NamedTextColor.GOLD,
    "Spin up and barrel through enemies in front of you at high speed.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    INTIMIDATION_AURA("Intimidation Aura", AbilityCategory.UTILITY, 25000, NamedTextColor.DARK_RED,
    "Project an aura of dominance that continuously weakens and damages all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CONQUEROR_STRIKE("Conqueror Strike", AbilityCategory.OFFENSE, 5000, NamedTextColor.RED,
    "A precise, devastating strike honed from centuries of combat experience.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    RUTHLESS_ASSAULT("Ruthless Assault", AbilityCategory.OFFENSE, 12000, NamedTextColor.DARK_RED,
    "Relentlessly assault a target with a rapid sequence of heavy blows.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    IMPERIAL_RAGE("Imperial Rage", AbilityCategory.OFFENSE, 15000, NamedTextColor.DARK_RED,
    "Unleash rage befitting Viltrum's greatest warrior, gaining immense strength briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    GROUND_POUND("Ground Pound", AbilityCategory.OFFENSE, 7000, NamedTextColor.RED,
    "Fly downward and slam the ground, creating a crater-like shockwave on impact.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    VILTRUMITE_CHARGE("Viltrumite Charge", AbilityCategory.MOBILITY, 5000, NamedTextColor.RED,
    "Accelerate horizontally at full Viltrumite velocity, crashing through any enemy in your path.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SUBJUGATION_GRIP("Subjugation Grip", AbilityCategory.UTILITY, 16000, NamedTextColor.DARK_RED,
    "Grab a nearby enemy and hurl them with overwhelming force.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SONIC_BOOM_PASS("Sonic Boom Pass", AbilityCategory.OFFENSE, 11000, NamedTextColor.RED,
    "Fly past the enemy so fast you create a sonic boom that deals area damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    MATTER_RESHAPE("Matter Reshape", AbilityCategory.UTILITY, 3000, NamedTextColor.LIGHT_PURPLE,
    "Reshape nearby blocks and matter, building instant cover or altering terrain.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ENERGY_SHIELD("Energy Shield", AbilityCategory.DEFENSE, 12000, NamedTextColor.AQUA,
    "Generate a barrier of atomic energy that absorbs incoming damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    HEALING_TOUCH("Healing Touch", AbilityCategory.DEFENSE, 10000, NamedTextColor.GREEN,
    "Channel atomic energy inward to rapidly heal your wounds.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MATTER_BLAST("Matter Blast", AbilityCategory.OFFENSE, 5000, NamedTextColor.LIGHT_PURPLE,
    "Reshape matter into a concentrated projectile and fire it at your target.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CONSTRUCT_ARMOR("Construct Armor", AbilityCategory.DEFENSE, 18000, NamedTextColor.YELLOW,
    "Form atomic matter around your body as temporary armour plating.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TRANSMUTE_GROUND("Transmute Ground", AbilityCategory.UTILITY, 8000, NamedTextColor.DARK_GREEN,
    "Transmute the ground under enemies into an unstable surface, slowing and damaging them.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ATOMIC_BURST("Atomic Burst", AbilityCategory.OFFENSE, 20000, NamedTextColor.LIGHT_PURPLE,
    "Release a massive omnidirectional burst of atomic energy, launching all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DIMENSIONAL_SHIFT("Dimensional Shift", AbilityCategory.MOBILITY, 8000, NamedTextColor.LIGHT_PURPLE,
    "Phase briefly into another dimension, becoming untargetable and teleporting a short distance.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ATOMIC_CAGE("Atomic Cage", AbilityCategory.UTILITY, 14000, NamedTextColor.LIGHT_PURPLE,
    "Form a cage of solid atomic matter around a nearby enemy, immobilising them briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    PINK_BEAM("Pink Beam", AbilityCategory.OFFENSE, 6000, NamedTextColor.LIGHT_PURPLE,
    "Fire a focused pink energy beam in your facing direction, damaging all in its path.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ATOMIC_FLIGHT("Atomic Flight", AbilityCategory.MOBILITY, 0, NamedTextColor.LIGHT_PURPLE,
    "Passive: Atom Eve can fly by reshaping the air around her. Double-jump to toggle flight.",
    "Passive ability. Double-jump to activate flight."),
    MATTER_WALL("Matter Wall", AbilityCategory.UTILITY, 10000, NamedTextColor.LIGHT_PURPLE,
    "Erect a wall of solid matter in front of you to block enemy projectiles and movement.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    EXPLOSIVE_CHARGE("Explosive Charge", AbilityCategory.OFFENSE, 4000, NamedTextColor.GOLD,
    "Infuse a thrown object with kinetic energy that detonates on contact.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    KINETIC_INFUSE("Kinetic Infuse", AbilityCategory.OFFENSE, 3000, NamedTextColor.YELLOW,
    "Charge your fists with explosive energy so your next melee strike detonates.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SPLODE_DASH("Splode Dash", AbilityCategory.MOBILITY, 6000, NamedTextColor.GOLD,
    "Propel yourself forward using a directed explosion at your feet.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CHAIN_EXPLOSION("Chain Explosion", AbilityCategory.OFFENSE, 12000, NamedTextColor.RED,
    "Create five sequential explosions in a ring around your position.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    GRENADE_VOLLEY("Grenade Volley", AbilityCategory.OFFENSE, 8000, NamedTextColor.GOLD,
    "Rapidly hurl multiple explosive charges at enemies in front of you.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DETONATION_FIELD("Detonation Field", AbilityCategory.OFFENSE, 15000, NamedTextColor.RED,
    "Create an area around you that continuously detonates enemies who enter.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    IMPACT_WAVE("Impact Wave", AbilityCategory.OFFENSE, 10000, NamedTextColor.GOLD,
    "Send a rolling explosion wave in your facing direction.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    REX_BURST("Rex Burst", AbilityCategory.OFFENSE, 25000, NamedTextColor.RED,
    "Release every stored kinetic charge at once in a massive omnidirectional explosion.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    PROXIMITY_MINE("Proximity Mine", AbilityCategory.UTILITY, 9000, NamedTextColor.YELLOW,
    "Plant an invisible explosive mine at your feet that triggers when enemies walk near it.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    KINETIC_SHIELD("Kinetic Shield", AbilityCategory.DEFENSE, 16000, NamedTextColor.YELLOW,
    "Wrap yourself in a kinetic barrier that absorbs and stores the next hit as explosive energy.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CLUSTER_BLAST("Cluster Blast", AbilityCategory.OFFENSE, 13000, NamedTextColor.RED,
    "Throw a cluster charge that splits into multiple sub-explosions mid-air.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CHARGE_SPRINT("Charge Sprint", AbilityCategory.MOBILITY, 7000, NamedTextColor.GOLD,
    "Sprint forward leaving a trail of micro-explosions behind you that damage pursuers.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    DRONE_SWARM("Drone Swarm", AbilityCategory.OFFENSE, 10000, NamedTextColor.AQUA,
    "Deploy a swarm of combat drones that repeatedly attack all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    FORCE_FIELD("Force Field", AbilityCategory.DEFENSE, 15000, NamedTextColor.DARK_AQUA,
    "Project a spherical force field around yourself that absorbs and reflects damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    LASER_ARRAY("Laser Array", AbilityCategory.OFFENSE, 6000, NamedTextColor.RED,
    "Fire a precision laser beam forward that burns and blinds anyone it strikes.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    NANITE_REPAIR("Nanite Repair", AbilityCategory.DEFENSE, 12000, NamedTextColor.GREEN,
    "Deploy internal nanites that rapidly repair your combat suit and heal damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    EMP_PULSE("EMP Pulse", AbilityCategory.UTILITY, 20000, NamedTextColor.YELLOW,
    "Release a broad electromagnetic pulse that slows and weakens all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TACTICAL_SCAN("Tactical Scan", AbilityCategory.UTILITY, 8000, NamedTextColor.AQUA,
    "Scan all nearby entities, displaying their health and position in chat.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MECH_OVERLOAD("Mech Overload", AbilityCategory.OFFENSE, 30000, NamedTextColor.RED,
    "Push your systems past their limit for extreme short-term power. Causes backlash damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ELECTROMAGNETIC_FIELD("Electromagnetic Field", AbilityCategory.DEFENSE, 15000, NamedTextColor.YELLOW,
    "Sustain a field around you that damages and slows any enemy who enters.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ROCKET_BARRAGE("Rocket Barrage", AbilityCategory.OFFENSE, 11000, NamedTextColor.RED,
    "Launch a rapid barrage of micro-rockets at all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    STEALTH_MODE("Stealth Mode", AbilityCategory.UTILITY, 18000, NamedTextColor.DARK_GRAY,
    "Activate optical camouflage, turning yourself invisible for a short period.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    GRAVITIC_SLAM("Gravitic Slam", AbilityCategory.OFFENSE, 9000, NamedTextColor.AQUA,
    "Use suit-mounted gravitic emitters to slam enemies into the ground.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SYSTEM_BOOST("System Boost", AbilityCategory.UTILITY, 14000, NamedTextColor.DARK_AQUA,
    "Overclock all suit systems simultaneously, enhancing speed, damage, and defence briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    DUPLICATE_SELF("Duplicate Self", AbilityCategory.UTILITY, 8000, NamedTextColor.YELLOW,
    "Create three visual copies of yourself that confuse enemies and serve as decoys.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SWARM_STRIKE("Swarm Strike", AbilityCategory.OFFENSE, 5000, NamedTextColor.GOLD,
    "All active duplicates rush the nearest enemy and strike simultaneously.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CLONE_SHIELD("Clone Shield", AbilityCategory.DEFENSE, 10000, NamedTextColor.YELLOW,
    "Surround yourself with clones that absorb the next several incoming hits.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MASS_ASSAULT("Mass Assault", AbilityCategory.OFFENSE, 15000, NamedTextColor.RED,
    "Direct every active duplicate to attack all nearby enemies at once.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DIVERSION_CLONE("Diversion Clone", AbilityCategory.UTILITY, 6000, NamedTextColor.YELLOW,
    "Place a single duplicate at your target location to draw enemy attention.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    PINCER_ATTACK("Pincer Attack", AbilityCategory.OFFENSE, 12000, NamedTextColor.GOLD,
    "Duplicates surround a single target and attack from all directions simultaneously.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CLONE_SURGE("Clone Surge", AbilityCategory.MOBILITY, 5000, NamedTextColor.WHITE,
    "Teleport to the position of the nearest active duplicate.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DUPLICATE_BURST("Duplicate Burst", AbilityCategory.OFFENSE, 20000, NamedTextColor.YELLOW,
    "All duplicates simultaneously detonate in a burst of concussive force.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CLONE_AMBUSH("Clone Ambush", AbilityCategory.OFFENSE, 11000, NamedTextColor.GOLD,
    "Duplicates phase in behind all nearby enemies and strike them from behind.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    INFINITE_COPIES("Infinite Copies", AbilityCategory.UTILITY, 22000, NamedTextColor.YELLOW,
    "Create a large number of duplicates that swarm the battlefield for several seconds.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    COPY_FADE("Copy Fade", AbilityCategory.MOBILITY, 7000, NamedTextColor.WHITE,
    "Vanish alongside all your copies, briefly turning invisible and resetting their positions.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BODY_DOUBLE("Body Double", AbilityCategory.DEFENSE, 13000, NamedTextColor.YELLOW,
    "Instantly create a copy that takes the next lethal hit in your place.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    MONSTER_TRANSFORM("Monster Transform", AbilityCategory.UTILITY, 20000, NamedTextColor.GREEN,
    "Transform into your massive monstrous form, gaining huge strength, size, and resilience.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    RAMPAGE("Rampage", AbilityCategory.OFFENSE, 10000, NamedTextColor.DARK_GREEN,
    "Strike all nearby enemies repeatedly in a burst of feral aggression.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    REGENERATE("Regenerate", AbilityCategory.DEFENSE, 15000, NamedTextColor.GREEN,
    "Monster physiology kicks in, rapidly regenerating health over a short period.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TREMOR_SLAM_MG("Monster Slam", AbilityCategory.OFFENSE, 8000, NamedTextColor.DARK_GREEN,
    "Slam enormous fists into the ground, knocking back and damaging all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MONSTER_ROAR("Monster Roar", AbilityCategory.UTILITY, 12000, NamedTextColor.DARK_GREEN,
    "Unleash a terrifying roar that disorients and slows all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TAIL_SWEEP("Tail Sweep", AbilityCategory.OFFENSE, 6000, NamedTextColor.GREEN,
    "Swing your massive tail in a wide arc, sending all nearby enemies flying.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    THICK_HIDE("Thick Hide", AbilityCategory.DEFENSE, 18000, NamedTextColor.GRAY,
    "Your monster form's hide becomes rock solid, drastically reducing damage taken briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    FERAL_CHARGE("Feral Charge", AbilityCategory.MOBILITY, 5000, NamedTextColor.GREEN,
    "Charge forward in monster form at tremendous speed, trampling anyone in your path.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MONSTER_LEAP("Monster Leap", AbilityCategory.MOBILITY, 7000, NamedTextColor.GREEN,
    "Leap an incredible distance in monster form, crashing down with impact damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CRUSHING_GRIP("Crushing Grip", AbilityCategory.OFFENSE, 9000, NamedTextColor.DARK_GREEN,
    "Grab a nearby enemy in your monstrous hands and squeeze, dealing heavy damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    EARTH_SHATTER("Earth Shatter", AbilityCategory.OFFENSE, 16000, NamedTextColor.DARK_GREEN,
    "Repeatedly slam the ground until a wide area of shockwaves spreads out.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BERSERK_ROAR("Berserk Roar", AbilityCategory.UTILITY, 24000, NamedTextColor.GREEN,
    "Roar so ferociously that all enemies in a wide radius are terrified, fleeing briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    ENERGY_DISCHARGE("Energy Discharge", AbilityCategory.OFFENSE, 5000, NamedTextColor.YELLOW,
    "Release a burst of stored bio-electric energy that damages nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SAMSON_CHARGE("Samson Charge", AbilityCategory.OFFENSE, 8000, NamedTextColor.DARK_GRAY,
    "Charge up your energy and release it in one devastating explosive strike.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    POWER_SLAM("Power Slam", AbilityCategory.OFFENSE, 6000, NamedTextColor.DARK_GRAY,
    "Slam energy-charged fists into the ground, sending shockwaves outward.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    LIGHTNING_STRIKE("Lightning Strike", AbilityCategory.OFFENSE, 10000, NamedTextColor.YELLOW,
    "Channel energy upward and call a lightning strike down on a targeted location.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ENERGY_BURST("Energy Burst", AbilityCategory.OFFENSE, 12000, NamedTextColor.GOLD,
    "Release stored energy in a massive omnidirectional burst.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    OVERCHARGE("Overcharge", AbilityCategory.OFFENSE, 25000, NamedTextColor.RED,
    "Push your power cells past their limit for a huge damage boost with a brief recovery penalty.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ENERGY_LANCE("Energy Lance", AbilityCategory.OFFENSE, 7000, NamedTextColor.YELLOW,
    "Condense energy into a forward-firing lance that pierces through multiple enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CHAIN_LIGHTNING("Chain Lightning", AbilityCategory.OFFENSE, 13000, NamedTextColor.YELLOW,
    "Release electricity that arcs between up to five nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    POWER_ARMOR("Power Armor", AbilityCategory.DEFENSE, 19000, NamedTextColor.DARK_GRAY,
    "Reinforce your body with a shell of compressed energy, blocking incoming damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ENERGY_VORTEX("Energy Vortex", AbilityCategory.UTILITY, 17000, NamedTextColor.YELLOW,
    "Create a vortex of energy that pulls enemies toward its centre before releasing them.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BATTLE_HARNESS("Battle Harness", AbilityCategory.UTILITY, 21000, NamedTextColor.DARK_GRAY,
    "Activate your GDA battle harness, boosting all stats for a short duration.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ELECTRIC_DASH("Electric Dash", AbilityCategory.MOBILITY, 6000, NamedTextColor.YELLOW,
    "Dash forward at electric speed, leaving a trail that shocks any enemy you pass through.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    BULLET_IMMUNITY("Bullet Immunity", AbilityCategory.DEFENSE, 20000, NamedTextColor.GRAY,
    "Activate bulletproof skin, reflecting all projectile damage back at attackers.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DEFLECT("Deflect", AbilityCategory.DEFENSE, 8000, NamedTextColor.WHITE,
    "Stance ready to deflect the next attack, sending its force back at the attacker.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    COUNTER_STRIKE("Counter Strike", AbilityCategory.OFFENSE, 6000, NamedTextColor.DARK_GREEN,
    "Brace for an incoming blow and respond with double the impact force.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    STEEL_SKIN("Steel Skin", AbilityCategory.DEFENSE, 15000, NamedTextColor.GRAY,
    "Harden skin to near-steel density, reducing all incoming damage for a short period.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    FORCE_RETURN("Force Return", AbilityCategory.OFFENSE, 10000, NamedTextColor.GREEN,
    "Absorb the damage from recent hits and fire all of it back at the nearest enemy.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    IMPACT_ABSORB("Impact Absorb", AbilityCategory.DEFENSE, 12000, NamedTextColor.GRAY,
    "Absorb incoming impact energy, converting it into regeneration.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ARMOR_SURGE("Armor Surge", AbilityCategory.DEFENSE, 18000, NamedTextColor.DARK_GRAY,
    "Surge armor density to maximum for a brief window, becoming nearly unbreakable.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    RICOCHET("Ricochet", AbilityCategory.OFFENSE, 8000, NamedTextColor.YELLOW,
    "Release all absorbed kinetic energy as an explosive burst targeting nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    IRON_RUSH("Iron Rush", AbilityCategory.MOBILITY, 6000, NamedTextColor.DARK_GREEN,
    "Charge forward with iron-hard body, dealing damage to any enemy in your path.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SKIN_FORTRESS("Skin Fortress", AbilityCategory.DEFENSE, 23000, NamedTextColor.GRAY,
    "Enter an ultra-hardened stance: greatly reduce damage but also slow your movement.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    REACTIVE_SHELL("Reactive Shell", AbilityCategory.DEFENSE, 14000, NamedTextColor.DARK_GREEN,
    "Coat yourself in a reactive shell that explodes outward when struck.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CONCUSSIVE_RETURN("Concussive Return", AbilityCategory.OFFENSE, 11000, NamedTextColor.GREEN,
    "Convert all recent absorbed impacts into a single concussive slam on the nearest enemy.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    RAPID_ADAPT("Rapid Adapt", AbilityCategory.DEFENSE, 15000, NamedTextColor.AQUA,
    "Your alien body rapidly adapts to the current damage type, granting resistance briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    COSMIC_PUNCH("Cosmic Punch", AbilityCategory.OFFENSE, 8000, NamedTextColor.DARK_AQUA,
    "Deliver a punch with the kinetic force of an interstellar traveller.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ADAPTATION_SHIELD("Adaptation Shield", AbilityCategory.DEFENSE, 20000, NamedTextColor.AQUA,
    "Generate an adaptive shield that adjusts to block whatever type of damage hits it.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    GALACTIC_BURST("Galactic Burst", AbilityCategory.OFFENSE, 25000, NamedTextColor.DARK_AQUA,
    "Release pent-up cosmic energy in a massive burst centred on yourself.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ALIEN_RESILIENCE("Alien Resilience", AbilityCategory.DEFENSE, 17000, NamedTextColor.AQUA,
    "Draw on alien physiology to regenerate health and resist all damage briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ORBIT_DASH("Orbit Dash", AbilityCategory.MOBILITY, 5000, NamedTextColor.DARK_AQUA,
    "Accelerate to orbital speed in a straight line, passing through enemies and damaging them.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    STELLAR_SLAM("Stellar_slam", AbilityCategory.OFFENSE, 11000, NamedTextColor.DARK_AQUA,
    "Crash downward from altitude at incredible speed, creating a star-impact shockwave.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    PAIN_THRESHOLD("Pain Threshold", AbilityCategory.DEFENSE, 22000, NamedTextColor.AQUA,
    "Embrace alien endurance: the more damage you take, the more your resistance increases.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    INTERSTELLAR_DASH("Interstellar Dash", AbilityCategory.MOBILITY, 7000, NamedTextColor.DARK_AQUA,
    "Propel yourself across a large distance almost instantaneously.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    COSMIC_ROAR("Cosmic Roar", AbilityCategory.UTILITY, 19000, NamedTextColor.AQUA,
    "Unleash a sonic roar amplified by alien physiology, stunning nearby enemies briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ALIEN_OVERDRIVE("Alien Overdrive", AbilityCategory.OFFENSE, 28000, NamedTextColor.DARK_AQUA,
    "Push alien physiology to its absolute limit, tripling damage output for several seconds.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    REGENERATIVE_SURGE("Regenerative Surge", AbilityCategory.DEFENSE, 13000, NamedTextColor.AQUA,
    "Trigger a rapid regenerative surge that heals a large amount of health instantly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    WAR_CRY("War Cry", AbilityCategory.UTILITY, 12000, NamedTextColor.RED,
    "Unleash a fearsome war cry that weakens all nearby enemies and boosts your resolve.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SAVAGE_STRIKE("Savage Strike", AbilityCategory.OFFENSE, 4000, NamedTextColor.DARK_RED,
    "Deliver a savage, unrestrained blow with the full force of a battle-hardened predator.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    UNYIELDING("Unyielding", AbilityCategory.DEFENSE, 18000, NamedTextColor.DARK_GRAY,
    "Brace yourself to refuse all knockback and greatly reduce damage briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MANE_SHIELD("Mane Shield", AbilityCategory.DEFENSE, 15000, NamedTextColor.YELLOW,
    "Your battle mane hardens into a natural shield, absorbing several incoming attacks.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    PREDATOR_LEAP("Predator Leap", AbilityCategory.MOBILITY, 5000, NamedTextColor.DARK_RED,
    "Leap a large distance toward the nearest enemy with predator-like precision.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    WARRIOR_BLOOD("Warrior Blood", AbilityCategory.DEFENSE, 20000, NamedTextColor.RED,
    "Your warrior heritage heals you as battle damage accumulates.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BATTLE_ROAR("Battle Roar", AbilityCategory.UTILITY, 25000, NamedTextColor.DARK_RED,
    "Roar with battle-fury, dramatically boosting your damage and speed for a short period.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    PRIMAL_FRENZY("Primal Frenzy", AbilityCategory.OFFENSE, 14000, NamedTextColor.DARK_RED,
    "Enter a primal frenzy, unleashing a rapid sequence of uncontrolled heavy strikes.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DEATH_CHARGE("Death Charge", AbilityCategory.MOBILITY, 8000, NamedTextColor.RED,
    "Charge at an enemy with kill-intent, dealing massive damage if you reach them.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BONE_CRUSH("Bone Crush", AbilityCategory.OFFENSE, 7000, NamedTextColor.DARK_RED,
    "Grab an enemy and apply crushing force, dealing heavy damage and applying slowness.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BEAST_ENDURANCE("Beast Endurance", AbilityCategory.DEFENSE, 21000, NamedTextColor.RED,
    "Draw on battle-hardened endurance to continue fighting even through devastating injury.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    KILLING_BLOW("Killing Blow", AbilityCategory.OFFENSE, 30000, NamedTextColor.DARK_RED,
    "A single strike with everything you have. If the target is below half health it is lethal.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    BATTLE_HARDENED("Battle Hardened", AbilityCategory.DEFENSE, 15000, NamedTextColor.DARK_RED,
    "Your countless scars harden your body, reducing incoming damage for a period.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SCAR_POWER("Scar Power", AbilityCategory.OFFENSE, 8000, NamedTextColor.RED,
    "Channel the power accumulated from every battle scar into your next strike.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CONQUEST_RAGE("Conquest Rage", AbilityCategory.OFFENSE, 20000, NamedTextColor.RED,
    "Enter a state of pure conquest rage, amplifying damage and removing all fear.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CONQUEROR_CHARGE("Conqueror Charge", AbilityCategory.MOBILITY, 6000, NamedTextColor.RED,
    "Charge forward at full Viltrumite velocity, bulldozing enemies in your path.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BLADE_SPIN("Blade Spin", AbilityCategory.OFFENSE, 9000, NamedTextColor.DARK_RED,
    "Spin with bladed gauntlets extended, damaging all nearby enemies in a wide arc.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DEVASTATION("Devastation", AbilityCategory.OFFENSE, 18000, NamedTextColor.RED,
    "Unleash a series of power strikes that stagger and damage every nearby enemy.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    IRON_WILL("Iron Will", AbilityCategory.DEFENSE, 24000, NamedTextColor.DARK_RED,
    "Ignore damage that would kill a lesser being. Survive one lethal blow.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    OPPRESSOR_GRIP("Oppressor Grip", AbilityCategory.UTILITY, 13000, NamedTextColor.RED,
    "Seize a nearby enemy and hurl them with tremendous force.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    VILTRUMITE_ENDURANCE("Viltrumite Endurance", AbilityCategory.DEFENSE, 18000, NamedTextColor.DARK_GRAY,
    "Draw on thousands of years of Viltrumite conditioning to shrug off damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    JUGULAR_STRIKE("Jugular Strike", AbilityCategory.OFFENSE, 8000, NamedTextColor.RED,
    "Strike the vital point with lethal precision. Deals critical damage to a single target.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    GRAND_REGENT_AURA("Grand Regent Aura", AbilityCategory.UTILITY, 20000, NamedTextColor.DARK_RED,
    "Project an aura of supreme authority. All nearby enemies are weakened and take damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    VILTRUMITE_MASTERY("Viltrumite Mastery", AbilityCategory.OFFENSE, 30000, NamedTextColor.RED,
    "Execute every mastered Viltrumite technique in one overwhelming assault.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SUPREME_AUTHORITY("Supreme Authority", AbilityCategory.UTILITY, 22000, NamedTextColor.DARK_RED,
    "Declare yourself supreme. All nearby enemies are simultaneously knocked back and weakened.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    LETHAL_DESCENT("Lethal Descent", AbilityCategory.OFFENSE, 12000, NamedTextColor.RED,
    "Dive from height at maximum speed and crater the ground, dealing massive area damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    REGENT_CHARGE("Regent Charge", AbilityCategory.MOBILITY, 5000, NamedTextColor.DARK_RED,
    "Accelerate at full grand-regent speed, crushing anything in your path.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    IRON_DYNASTY("Iron Dynasty", AbilityCategory.DEFENSE, 26000, NamedTextColor.DARK_RED,
    "Project the will of Viltrum's dynasty, dramatically reducing all incoming damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SOVEREIGN_SLAM("Sovereign Slam", AbilityCategory.OFFENSE, 10000, NamedTextColor.RED,
    "Slam the earth with the force of a supreme ruler, creating wide ground shockwaves.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    WARLORD_WRATH("Warlord Wrath", AbilityCategory.OFFENSE, 16000, NamedTextColor.DARK_RED,
    "Channel the full wrath of the most powerful Viltrumite into a devastating barrage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    EDICT("Edict", AbilityCategory.UTILITY, 28000, NamedTextColor.RED,
    "Issue a supreme edict. All nearby enemies are frozen in place briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CULLING_STRIKE("Culling Strike", AbilityCategory.OFFENSE, 20000, NamedTextColor.DARK_RED,
    "Strike with the intent to remove weakness. Executes enemies below 25% health.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    DIMENSION_PORTAL("Dimension Portal", AbilityCategory.MOBILITY, 6000, NamedTextColor.DARK_PURPLE,
    "Open a rift to another dimension and step through, teleporting to your look direction target.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MULTIVERSE_DRAIN("Multiverse Drain", AbilityCategory.OFFENSE, 15000, NamedTextColor.DARK_PURPLE,
    "Drain life force from alternate-universe versions of nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    KNOWLEDGE_SURGE("Knowledge Surge", AbilityCategory.UTILITY, 10000, NamedTextColor.LIGHT_PURPLE,
    "Absorb multiverse knowledge to temporarily enhance your speed and reaction time.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    PORTAL_TRAP("Portal Trap", AbilityCategory.UTILITY, 12000, NamedTextColor.DARK_PURPLE,
    "Plant a portal trap at target location. The next enemy to step on it is teleported high up.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    INTELLECT_BLAST("Intellect Blast", AbilityCategory.OFFENSE, 10000, NamedTextColor.DARK_PURPLE,
    "Focus the combined intellect of the multiverse into a destructive mental blast.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CROSS_DIMENSION("Cross Dimension", AbilityCategory.UTILITY, 20000, NamedTextColor.LIGHT_PURPLE,
    "Pull in temporary versions of yourself from alternate dimensions as fighter copies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    REALITY_TEAR("Reality Tear", AbilityCategory.OFFENSE, 30000, NamedTextColor.DARK_PURPLE,
    "Tear the fabric of reality itself, dealing massive damage in a large area.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MULTIVERSE_STEP("Multiverse Step", AbilityCategory.MOBILITY, 4000, NamedTextColor.LIGHT_PURPLE,
    "Step sideways through the multiverse, instantly reappearing a short distance away.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    PARALLEL_STRIKE("Parallel Strike", AbilityCategory.OFFENSE, 9000, NamedTextColor.DARK_PURPLE,
    "Versions of yourself from other dimensions all strike the same enemy simultaneously.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DIMENSIONAL_ANCHOR("Dimensional Anchor", AbilityCategory.UTILITY, 16000, NamedTextColor.LIGHT_PURPLE,
    "Anchor an enemy to this dimension, preventing them from moving or dodging briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    RIFT_SHIELD("Rift Shield", AbilityCategory.DEFENSE, 17000, NamedTextColor.DARK_PURPLE,
    "Open a dimensional rift in front of you that absorbs incoming projectiles and attacks.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    VOID_PULL("Void Pull", AbilityCategory.UTILITY, 13000, NamedTextColor.DARK_PURPLE,
    "Open a void rift that pulls all nearby enemies toward a central point.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    MINIATURIZE("Miniaturize", AbilityCategory.MOBILITY, 8000, NamedTextColor.WHITE,
    "Shrink to near-microscopic size, becoming invisible and very fast, but fragile.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MICRO_STRIKE("Micro Strike", AbilityCategory.OFFENSE, 5000, NamedTextColor.WHITE,
    "While tiny, slip inside the nearest enemy and strike a vital internal point.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SIZE_SHIFT("Size Shift", AbilityCategory.UTILITY, 6000, NamedTextColor.GRAY,
    "Rapidly alternate size several times, confusing enemies and making yourself hard to hit.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    INTERNAL_ATTACK("Internal Attack", AbilityCategory.OFFENSE, 10000, NamedTextColor.RED,
    "Phase into a miniaturized form inside an enemy and deal critical internal damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SHRINK_DASH("Shrink Dash", AbilityCategory.MOBILITY, 4000, NamedTextColor.WHITE,
    "Shrink momentarily and dash forward, phasing through any obstacle.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    GIANT_FORM("Giant Form", AbilityCategory.OFFENSE, 20000, NamedTextColor.DARK_GRAY,
    "Grow to enormous size with massively increased damage and knockback range.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SIZE_WAVE("Size Wave", AbilityCategory.OFFENSE, 15000, NamedTextColor.WHITE,
    "Emit a wave of size-altering energy that weakens and disorients all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MICRO_BURST("Micro Burst", AbilityCategory.OFFENSE, 25000, NamedTextColor.WHITE,
    "Expand at ultra speed while inside an enemy, dealing massive internal burst damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SHRINK_BOMB("Shrink Bomb", AbilityCategory.UTILITY, 11000, NamedTextColor.GRAY,
    "Throw a size-altering charge that shrinks the first enemy it hits briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    GIANT_STOMP("Giant Stomp", AbilityCategory.OFFENSE, 9000, NamedTextColor.DARK_GRAY,
    "In giant form, stomp the ground to create a massive shockwave in all directions.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    PHASE_DODGE("Phase Dodge", AbilityCategory.DEFENSE, 12000, NamedTextColor.WHITE,
    "Shrink just long enough to phase through an incoming attack, dodging it entirely.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TITAN_SLAM("Titan Slam", AbilityCategory.OFFENSE, 18000, NamedTextColor.DARK_GRAY,
    "Grow to giant size and deliver a two-handed slam that devastates a large area.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    TACTICAL_COMMAND("Tactical Command", AbilityCategory.UTILITY, 12000, NamedTextColor.GRAY,
    "Issue precise tactical commands, boosting damage for all nearby allied players.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SHIELD_DEPLOY("Shield Deploy", AbilityCategory.DEFENSE, 15000, NamedTextColor.GRAY,
    "Deploy a GDA energy barrier that protects you and nearby allies from damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    WEAPON_MASTERY("Weapon Mastery", AbilityCategory.OFFENSE, 5000, NamedTextColor.DARK_GRAY,
    "Apply advanced weapons training to massively increase your melee damage briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    STRATEGIC_STRIKE("Strategic Strike", AbilityCategory.OFFENSE, 8000, NamedTextColor.GRAY,
    "Identify and attack the most vulnerable point of the nearest enemy.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    COORDINATED_ASSAULT("Coordinated Assault", AbilityCategory.OFFENSE, 12000, NamedTextColor.DARK_GRAY,
    "Execute a perfectly coordinated tactical strike against a target.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    FIELD_MEDIC("Field Medic", AbilityCategory.DEFENSE, 10000, NamedTextColor.GREEN,
    "Apply GDA field medic techniques to rapidly restore your health.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    INTEL_SCAN("Intel Scan", AbilityCategory.UTILITY, 6000, NamedTextColor.AQUA,
    "Conduct a GDA intelligence sweep, revealing enemy health and positions in chat.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    GOVERNMENT_BACKUP("Government Backup", AbilityCategory.UTILITY, 30000, NamedTextColor.DARK_GRAY,
    "Call in GDA emergency support, temporarily enhancing all your stats.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TACTICAL_RETREAT("Tactical Retreat", AbilityCategory.MOBILITY, 8000, NamedTextColor.GRAY,
    "Execute a fast tactical withdrawal, dashing backward and breaking enemy engagement.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SUPPRESSION_FIRE("Suppression Fire", AbilityCategory.UTILITY, 11000, NamedTextColor.DARK_GRAY,
    "Lay down suppressive fire that slows all enemies in a cone in front of you.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    COUNTER_INTEL("Counter Intel", AbilityCategory.DEFENSE, 16000, NamedTextColor.GRAY,
    "Anticipate enemy movements, gaining a brief window of total damage immunity.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ASSET_EXTRACTION("Asset Extraction", AbilityCategory.MOBILITY, 20000, NamedTextColor.DARK_GRAY,
    "Trigger an emergency GDA extraction protocol, teleporting you to safety.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    GDA_AIRSTRIKE("GDA Airstrike", AbilityCategory.OFFENSE, 25000, NamedTextColor.DARK_GRAY,
    "Call in a GDA air strike. Mark your target location — a massive explosion hits 2 seconds later.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DRONE_BARRAGE("Drone Barrage", AbilityCategory.OFFENSE, 18000, NamedTextColor.GRAY,
    "Deploy three assault drones that hunt and attack the nearest enemies independently.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    FREEZE_ASSETS("Freeze Assets", AbilityCategory.UTILITY, 20000, NamedTextColor.DARK_AQUA,
    "GDA authority freezes one nearby target completely — they cannot move or act for several seconds.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    RED_TAPE("Red Tape", AbilityCategory.UTILITY, 15000, NamedTextColor.RED,
    "Bury all nearby enemies in bureaucratic red tape — maximum slowness and weakness for a duration.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    NANITE_INJECTION("Nanite Injection", AbilityCategory.DEFENSE, 16000, NamedTextColor.AQUA,
    "Inject GDA medical nanites — you regenerate health rapidly for a sustained duration.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    LOCKDOWN("Lockdown", AbilityCategory.UTILITY, 22000, NamedTextColor.DARK_GRAY,
    "Declare a full GDA lockdown — all enemies in range are severely slowed and weakened.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    FIELD_COMMANDER("Field Commander", AbilityCategory.UTILITY, 30000, NamedTextColor.GOLD,
    "Assume field command — grant all nearby players a damage and speed buff for a duration.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BLACK_SITE("Black Site", AbilityCategory.MOBILITY, 12000, NamedTextColor.DARK_GRAY,
    "Invoke black-site protocol — teleport the nearest enemy 15 blocks above the ground.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CLASSIFIED("Classified", AbilityCategory.DEFENSE, 25000, NamedTextColor.DARK_GRAY,
    "Access classified GDA countermeasures — instantly clear all debuffs and become immune briefly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    AUTHORITY_OVERRIDE("Authority Override", AbilityCategory.OFFENSE, 14000, NamedTextColor.GRAY,
    "Override enemy combat readiness with GDA authority — nearby enemies are disoriented and take bonus damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    KINETIC_RELEASE("Kinetic Release", AbilityCategory.OFFENSE, 12000, NamedTextColor.DARK_GREEN,
    "Release all stored kinetic energy at once in a devastating point-blank explosion.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SHOCKWAVE_FIST("Shockwave Fist", AbilityCategory.OFFENSE, 7000, NamedTextColor.DARK_GREEN,
    "Throw a punch so hard it creates a visible shockwave that travels forward dealing damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    IMPENETRABLE("Impenetrable", AbilityCategory.DEFENSE, 30000, NamedTextColor.WHITE,
    "Plant your feet and become completely immune for 5 seconds — you cannot move while active.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BULLET_CATCH("Bullet Catch", AbilityCategory.DEFENSE, 14000, NamedTextColor.DARK_GREEN,
    "Enter a catch stance — the next hit you take is absorbed and returned to the attacker with double force.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    MOMENTUM_TRANSFER("Momentum Transfer", AbilityCategory.OFFENSE, 8000, NamedTextColor.DARK_GREEN,
    "Transfer your full body momentum directly into a target — they fly back with catastrophic force.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    UNSTOPPABLE("Unstoppable", AbilityCategory.MOBILITY, 14000, NamedTextColor.DARK_GREEN,
    "Charge forward — nothing slows, stops, or knocks you back. You pass through entities dealing damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    IRON_DENSITY("Iron Density", AbilityCategory.UTILITY, 18000, NamedTextColor.DARK_GREEN,
    "Massively increase your personal density — become immune to all knockback and movement effects.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    KINETIC_FEEDBACK("Kinetic Feedback", AbilityCategory.UTILITY, 20000, NamedTextColor.DARK_GREEN,
    "Every hit you absorb during the next 6 seconds is tallied and dealt back in one devastating counter.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TITANIUM_RUSH("Titanium Rush", AbilityCategory.MOBILITY, 6000, NamedTextColor.DARK_GREEN,
    "Sprint at bullet speed, slamming into the first enemy you hit for massive impact damage.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DENSITY_SLAM("Density Slam", AbilityCategory.OFFENSE, 9000, NamedTextColor.DARK_GREEN,
    "Slam downward at maximum density — the ground impact creates a massive crater-scale shockwave.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    ANCIENT_FURY("Ancient Fury", AbilityCategory.OFFENSE, 12000, NamedTextColor.GOLD,
    "Millennia of combat experience erupt in a single devastating blow that staggers every enemy in range.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TIME_HARDENED("Time Hardened", AbilityCategory.DEFENSE, 25000, NamedTextColor.YELLOW,
    "Shrug off damage through sheer ancient endurance. The older the warrior, the stronger this gets.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    RESURRECTION_SURGE("Resurrection Surge", AbilityCategory.DEFENSE, 60000, NamedTextColor.WHITE,
    "Draw on your legendary immortality. When triggered near death, heal a large portion of health instantly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TIMELESS_STRIKE("Timeless Strike", AbilityCategory.OFFENSE, 8000, NamedTextColor.GOLD,
    "A strike refined over thousands of years. Deals bonus damage based on your missing health.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    UNDYING_WILL("Undying Will", AbilityCategory.DEFENSE, 30000, NamedTextColor.YELLOW,
    "You simply refuse to stay down. Gain total damage immunity for a brief moment.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    ANCIENT_LEAP("Ancient Leap", AbilityCategory.MOBILITY, 6000, NamedTextColor.GOLD,
    "Launch yourself at an enemy with the accumulated power of an immortal warrior.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    GRAPPLE_LINE("Grapple Line", AbilityCategory.MOBILITY, 4000, NamedTextColor.DARK_GRAY,
    "Fire a grapple hook to pull yourself toward a nearby surface or enemy.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SMOKE_BOMB("Smoke Bomb", AbilityCategory.UTILITY, 14000, NamedTextColor.GRAY,
    "Deploy a smoke bomb that blinds all enemies in the area and grants you brief invisibility.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    WING_STRIKE("Wing Strike", AbilityCategory.OFFENSE, 6000, NamedTextColor.DARK_GRAY,
    "Snap your cape forward with enough force to knock an enemy off their feet.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    BATARANG_VOLLEY("Batarang Volley", AbilityCategory.OFFENSE, 9000, NamedTextColor.GRAY,
    "Hurl a spread of razor-edged projectiles that damage and slow all enemies in front of you.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    DARK_SILENCE("Dark Silence", AbilityCategory.UTILITY, 18000, NamedTextColor.DARK_GRAY,
    "Vanish into shadow, granting invisibility and silencing your footsteps momentarily.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    CAPE_GLIDE("Cape Glide", AbilityCategory.MOBILITY, 5000, NamedTextColor.GRAY,
    "Spread your cape and glide, covering ground quickly while descending slowly.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    BLUE_FLAME("Blue Flame", AbilityCategory.OFFENSE, 7000, NamedTextColor.AQUA,
    "Unleash a searing blast of blue-white alien fire that burns enemies over time.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    HALF_BREED_SURGE("Half-Breed Surge", AbilityCategory.OFFENSE, 18000, NamedTextColor.BLUE,
    "Tap into your mixed Viltrumite heritage for a burst of power beyond your normal limits.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    HEAT_VISION("Heat Vision", AbilityCategory.OFFENSE, 8000, NamedTextColor.RED,
    "Focus your gaze and fire twin beams of superheated energy at your target.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    SUPER_BREATH("Super Breath", AbilityCategory.UTILITY, 12000, NamedTextColor.WHITE,
    "Exhale a gust of superhumanly powerful breath that pushes enemies back and slows them.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    TECH_JACKET_BOOST("Tech Jacket Boost", AbilityCategory.MOBILITY, 5000, NamedTextColor.AQUA,
    "Trigger your Tech Jacket's thruster array for a sudden burst of flight speed.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),
    FULL_POWER("Full Power", AbilityCategory.OFFENSE, 45000, NamedTextColor.BLUE,
    "Stop holding back. Release your full strength in a single catastrophic strike on all nearby enemies.",
    "Left-click or press F (swap hands) while on the hotbar slot this is bound to."),

    AERIAL_GRAB("Aerial Grab", AbilityCategory.UTILITY, 12000, NamedTextColor.AQUA,
    "While flying, grab a nearby target and carry them through the air, dealing damage every tick. Duration and damage scale with stats.",
    "Left-click while flying on the hotbar slot this is bound to."),
    AERIAL_SLAM("Aerial Slam", AbilityCategory.OFFENSE, 10000, NamedTextColor.DARK_AQUA,
    "While flying, dive-bomb a nearby target and slam them into the ground with crushing force. Works on airborne targets.",
    "Left-click while flying on the hotbar slot this is bound to."),

    CONFIG_ABILITY("Config Ability", AbilityCategory.OFFENSE, 0, NamedTextColor.YELLOW,
    "A custom ability created in-game via the Ability Creator.",
    "Use from your hotbar slot."),

    GENERIC_DASH("Quick Dash", AbilityCategory.MOBILITY, 3000, NamedTextColor.GRAY,
    "Dash 4-5 blocks in your facing direction. Available in slot 5 for all characters.",
    "Hold hotbar slot 5 and left-click, F, or Q."),
    GRAPPLE("Grapple", AbilityCategory.UTILITY, 5000, NamedTextColor.YELLOW,
    "Lunge and grab the nearest enemy, trading blows like a boxing clinch before a finishing slam.",
    "Hold hotbar slot 6 and left-click to grapple. Left-click again to slam. Sneak to break."),

    VACUUM_PUNCH("Vacuum Punch", AbilityCategory.OFFENSE, 18000, NamedTextColor.RED,
    "Create a vacuum shockwave that pulls all nearby players and entities toward you, then punches them for massive damage.",
    "Left-click or press F while on the hotbar slot this is bound to.");

    private final String displayName;
    private final AbilityCategory category;
    private final long cooldownMs;
    private final NamedTextColor color;
    private final String description;
    private final String activation;

    AbilityType(String displayName, AbilityCategory category, long cooldownMs,
    NamedTextColor color, String description, String activation) {
        this.displayName = displayName;
        this.category = category;
        this.cooldownMs = cooldownMs;
        this.color = color;
        this.description = description;
        this.activation = activation;
    }

    public String getDisplayName(){
        return displayName;
    }
    public AbilityCategory getCategory(){
        return category;
    }
    public long getCooldownMs(){
        return cooldownMs;
    }
    public NamedTextColor getColor(){
        return color;
    }
    public String getDescription(){
        return description;
    }
    public String getActivation(){
        return activation;
    }

    public static class ConfigAbilityMeta {
        public final String key;
        public final String displayName;
        public final AbilityCategory category;
        public final long cooldownMs;
        public final net.kyori.adventure.text.format.NamedTextColor color;
        public final String description;
        public final java.util.List<String> effects;
        public final java.util.List<String> allowedCharacters;

        public ConfigAbilityMeta(String key, String displayName, AbilityCategory category,
        long cooldownMs, net.kyori.adventure.text.format.NamedTextColor color,
        String description, java.util.List<String> effects,
        java.util.List<String> allowedCharacters) {
            this.key = key;
            this.displayName = displayName;
            this.category = category;
            this.cooldownMs = cooldownMs;
            this.color = color;
            this.description = description;
            this.effects = effects;
            this.allowedCharacters = allowedCharacters;
        }
    }

    private static final java.util.Map<String, ConfigAbilityMeta> CONFIG_REGISTRY = new java.util.LinkedHashMap<>();

    public static void registerConfigAbility(ConfigAbilityMeta meta) {
        CONFIG_REGISTRY.put(meta.key.toUpperCase(), meta);
    }

    public static void clearConfigRegistry() {
        CONFIG_REGISTRY.clear();
    }

    public static java.util.Map<String, ConfigAbilityMeta> getConfigAbilities() {
        return CONFIG_REGISTRY;
    }

    public static ConfigAbilityMeta getConfigMeta(String key) {
        return CONFIG_REGISTRY.get(key.toUpperCase());
    }

    public static boolean isConfigAbility(String key) {
        return CONFIG_REGISTRY.containsKey(key.toUpperCase());
    }

    public static AbilityType fromName(String name) {
        if (name == null) return null;
        for (AbilityType type : values()) {
            if (type.name().equalsIgnoreCase(name)) return type;
            if (type.displayName.equalsIgnoreCase(name)) return type;
        }
        if (CONFIG_REGISTRY.containsKey(name.toUpperCase())) return CONFIG_ABILITY;
        for (ConfigAbilityMeta meta : CONFIG_REGISTRY.values()) {
            if (meta.displayName.equalsIgnoreCase(name)) return CONFIG_ABILITY;
        }
        return null;
    }
}